"""Candidate actions generated by Vector planning."""

from __future__ import annotations

from dataclasses import dataclass, field

from blackline.clt.ir import ActionIntent


@dataclass(frozen=True, slots=True)
class Candidate:
    """A deduplicable, explainable action that Vector could execute next."""

    capability_id: str
    intent: ActionIntent
    target: str
    reason: tuple[str, ...]
    sources: tuple[str, ...] = field(default_factory=tuple)
    score: int = 0

    @property
    def identity(self) -> str:
        """Return a stable identity for queueing and execution history."""
        return f"{self.capability_id}|{self.target}"
