import unittest
from pathlib import Path


class StructureTests(unittest.TestCase):
    def test_requested_structure_exists(self):
        root = Path(__file__).resolve().parents[1] / "blackline"
        expected = [
            "cli/cli.py",
            "cli/core_shell.py",
            "cli/ui/elements.py",
            "cli/ui/colors.py",
            "cli/ui/display.py",
            "cli/commands/system",
            "cli/commands/recon",
            "cli/commands/network",
            "cli/commands/utils",
            "cli/commands/templates",
            "cli/parser/intent_parser.py",
            "cli/parser/tokenizer.py",
            "vector/vector.py",
            "vector/goal.py",
            "vector/state.py",
            "vector/observation.py",
            "vector/capability.py",
            "vector/resolver.py",
            "vector/planner.py",
            "vector/candidate.py",
            "vector/scorer.py",
            "vector/policy.py",
            "vector/decision.py",
            "clt/lexer.py",
            "clt/tokens.py",
            "clt/vocabulary.py",
            "clt/parser.py",
            "clt/ast.py",
            "clt/normalize.py",
            "clt/validator.py",
            "clt/ir.py",
            "clt/compiler.py",
            "clt/runtime.py",
            "clt/errors.py",
            "engine/context.py",
            "engine/runner.py",
            "engine/planner.py",
            "engine/executor.py",
            "engine/pipeline.py",
            "engine/session.py",
            "tools/network/nmap.py",
            "tools/network/rpcinfo.py",
            "tools/dns/subfinder.py",
            "tools/tls/sslyze.py",
            "tools/http/curl_probe.py",
            "tools/http/httpx.py",
            "tools/http/whatweb.py",
            "tools/http/katana.py",
            "tools/installer.py",
            "tools/parsers/nmap.py",
            "tools/parsers/rpcinfo.py",
            "tools/parsers/subfinder.py",
            "tools/parsers/curl.py",
            "tools/parsers/httpx.py",
            "tools/parsers/whatweb.py",
            "tools/parsers/sslyze.py",
            "tools/parsers/katana.py",
            "operators/background.py",
            "operators/parallel.py",
            "operators/sequence.py",
            "operators/conditional.py",
            "config/commands.json",
            "config/operators.json",
            "config/tools.json",
            "config/tool_installers.json",
            "config/defaults.json",
            "config/global.json",
            "config/vector/recon.json",
            "storage/database",
            "storage/cache",
            "utils/exec.py",
            "utils/string_matcher.py",
            "utils/tab_complete.py",
            "templates/models.py",
            "templates/registry.py",
            "templates/storage.py",
        ]

        for path in expected:
            with self.subTest(path=path):
                self.assertTrue((root / path).exists())


if __name__ == "__main__":
    unittest.main()
